services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://matches:8AJ60qlq9Horkb4T@cluster0.2qazv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - frontend

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://matches:8AJ60qlq9Horkb4T@cluster0.2qazv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    stdin_open: true
    tty: true
  
  

